# cloudbuild.yaml
on:
  push:
    branches: [main]
env:
  PROJECT_ID: tactical-grid-435414-s9 
  REPOSITORY_NAME: Personal_Website-Backend
  REGION: europe-west2
  IMAGE_NAME: fastapi-app

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    environment: GCP-env

  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/tactical-grid-435414-s9/fastapi-app:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tactical-grid-435414-s9/fastapi-app:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastapi-app'
      - '--image'
      - 'gcr.io/tactical-grid-435414-s9/fastapi-app:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'  # Specify your preferred region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'  # Matching the port specified in your Dockerfile

# The following are required environment variables:
# $PROJECT_ID: Your Google Cloud project ID
# $COMMIT_SHA: The git commit SHA that triggered the build

images:
  - 'gcr.io/tactical-grid-435414-s9/fastapi-app:$COMMIT_SHA'
